### ISSUE TITLE
如何在本地运行serving的开发环境

### ISSUE THREAD

**Issue by killomsc** [secretflow/serving#114]
不熟悉C++的开发环境，请问下如果想在本地调试下serving，如何配置开发环境少走弯路。

**Comment by BrainWH** [comment]
serving可以生成debug应用程序，用gdb调试就可以，环境需要bazel，类似cmake的编译工具

**Comment by killomsc** [comment]
@BrainWH 可以通过vscode配置，然后在vscode调试吗？

**Comment by BrainWH** [comment]
是的，可以的
