### ISSUE TITLE
编译serving报错

### ISSUE THREAD

**Issue by ougyou** [secretflow/serving#122]
根据文档描述编译报错
https://github.com/secretflow/serving/blob/main/CONTRIBUTING.md#build

![image](https://github.com/user-attachments/assets/3cb48ce0-281f-4e17-ba67-c02ee029ada0)

使用命令bazel build //... -c opt
![image](https://github.com/user-attachments/assets/7fc26c8f-7718-4037-bcd7-8f982259b39d)

能否直接提供编译好的simple_feature_service模块能力呢，有java或python版本的simple_feature_service么

**Comment by zimu-yuxi** [comment]
1.建议参考这里的[环境依赖](https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l#c5jHC)版本，修改下对应版本
2.暂时没有java或python版本的simple_feature_service

**Comment by ougyou** [comment]
> 1.建议参考这里的[环境依赖](https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l#c5jHC)版本，修改下对应版本 2.暂时没有java或python版本的simple_feature_service

能否把已经编译好的simple_feature_service  c++程序提供一份

**Comment by ougyou** [comment]
0.7.0b0，可以提供这个版本的编译环境依赖么
