### ISSUE TITLE
使用csvoption报错；服务起来运行OK了，但是请求的时候报错

### ISSUE THREAD

**Issue by john8628** [secretflow/serving#127]
serving.config配置文件如下
··
{
  "id": "gfgcobpo",
  "serverConf": {
    "featureMapping": {
      "duration": "duration",
      "month": "month",
      "contact":"contact",
      "y":"y",
      "day":"day",
      "poutcome":"poutcome"
    },
    "host": "0.0.0.0",
    "servicePort": "9011",
    "communicationPort": "9111",
    "metricsExposerPort": 10309,
    "brpcBuiltinServicePort": 10310
  },
  "modelConf": {
    "modelId": "xxxc-cvra-model-export",
    "basePath": "./data",
    "sourcePath": "/root/model_bundle.tar.gz",
    "sourceSha256": "7873f4b1a86f496c37380245c76ad41add8e28f50c0211e595b29f9dcf36b4af",
    "sourceType": "ST_FILE"
  },
  "clusterConf": {
    "selfId": "xxj",
    "parties": [
      {
        "id": "xxj",
        "address": "0.0.0.0:9111"
      },
      {
        "id":"trans",
        "address":"10.46.139.1:9110"
      }
    ],
    "channelDesc": {
      "protocol": "http"
    }
  },
  "featureSourceConf": {
    "csvOpts": {
      "file_path":"/root/krjs_afejrcxz_node_42_output_1",
      "id_name":"gaid2"
    }
  }
}
··

http命令 ： {
  "id": "gfgcobpo",
  "serverConf": {
    "featureMapping": {
      "duration": "duration",
      "month": "month",
      "contact":"contact",
      "y":"y",
      "day":"day",
      "poutcome":"poutcome"
    },
    "host": "0.0.0.0",
    "servicePort": "9011",
    "communicationPort": "9111",
    "metricsExposerPort": 10309,
    "brpcBuiltinServicePort": 10310
  },
  "modelConf": {
    "modelId": "xxxc-cvra-model-export",
    "basePath": "./data",
    "sourcePath": "/root/model_bundle.tar.gz",
    "sourceSha256": "7873f4b1a86f496c37380245c76ad41add8e28f50c0211e595b29f9dcf36b4af",
    "sourceType": "ST_FILE"
  },
  "clusterConf": {
    "selfId": "xxj",
    "parties": [
      {
        "id": "xxj",
        "address": "0.0.0.0:9111"
      },
      {
        "id":"trans",
        "address":"10.46.139.1:9110"
      }
    ],
    "channelDesc": {
      "protocol": "http"
    }
  },
  "featureSourceConf": {
    "csvOpts": {
      "file_path":"/root/krjs_afejrcxz_node_42_output_1",
      "id_name":"gaid2"
    }
  }
}

报错信息 ： {"header":{"data":{}},"status":{"code":3,"msg":"[secretflow_serving/framework/execute_context.cc:197] xxj exec failed: code(3), [Enforce fail at secretflow_serving/util/arrow_helper.cc:404] is_in_array->true_count() == is_in_array->length(). query data row ids:gaid2,duration,month,contact,y,day,poutcome,marital,job do not all exists in id column of csv file, match count: 0."},"service_spec":{"id":"gfgcobpo"}}

**Comment by wangzul** [comment]
Serving使用方式是怎样的？kuscia 注册内部调用serving  还是docker 部署的serving服务。

**Comment by wangzul** [comment]
Serving镜像版本是多少？

**Comment by john8628** [comment]
> uscia 注册内部调用serving 还是docker 部署的serving服务。

docker 部署的serving服务，前几天拉取的 lastest镜像;应该是 0.7.0b0

**Comment by wangzul** [comment]
> > uscia 注册内部调用serving 还是docker 部署的serving服务。
> 
> docker 部署的serving服务，前几天拉取的 lastest镜像;应该是 0.7.0b0

请求的参数方便提供一下吗

**Comment by john8628** [comment]
> /root/krjs_afejrcxz_node_42_output_1 数据文件方便给一下吗

(base) [root@vm_0_1_centos ~/serving/examples/palmpay_more_data] eth0 
# head krjs_afejrcxz_node_42_output_1 
contact,day,month,duration,campaign,pdays,previous,poutcome,y,gaid2
unknown,9,5,126,2,-1,0,unknown,0,0025d919-90d6-4b4e-907c-ee9c984ad425
cellular,15,5,339,4,-1,0,unknown,0,01d0615a-9828-4019-971e-356f775422b0
cellular,21,11,151,1,-1,0,unknown,0,0149ba36-017f-47cb-a1fa-c4af94c0f7a5
cellular,7,8,414,4,-1,0,unknown,0,00f3b7ac-a074-40e6-98ac-99a5a38f1cab
unknown,27,5,62,13,-1,0,unknown,0,005ad8f7-37f9-4170-b4ff-55846e5fb566
cellular,18,11,346,1,-1,0,unknown,0,01331e50-dbda-493a-a63b-c5ee4bd35ed5
cellular,14,4,283,2,-1,0,unknown,0,01831add-817c-4b12-9e87-75ccef12ef9f
cellular,6,5,222,1,-1,0,unknown,0,01a2fd1c-6c7c-4df3-918e-d26906ba7e29
unknown,23,6,655,4,-1,0,unknown,0,009e87e7-3db7-4035-ab08-69d2f8abda6a

**Comment by john8628** [comment]
csv_opt中请求的列必须是定义的主键
