### ISSUE TITLE
serving推理报超时，但是实际是两方通信的

### ISSUE THREAD

**Issue by neaos** [secretflow/serving#131]
![image](https://github.com/user-attachments/assets/286373d4-7344-4c86-be2a-fbe7daed26d5)

**Comment by neaos** [comment]
前面的数据查询比较慢会影响吗，哪里能调整响应时间

**Comment by neaos** [comment]
感觉像是超过20秒就断

**Comment by neaos** [comment]
<img width="1057" alt="631ea883d9fd5a2f986f2e8bd470b5f" src="https://github.com/user-attachments/assets/5e182a30-ac80-444a-a39a-33838935a58b" />

发起方是10:42:54报超时

**Comment by neaos** [comment]
联邦方最后日志时间是10:43:10响应
<img width="502" alt="0aba000df3348722b0f0aa83b2c0a89" src="https://github.com/user-attachments/assets/e83b53c2-6e5e-4f8f-ba18-53a2704ed496" />

**Comment by oeqqwq** [comment]
可以查看https://www.secretflow.org.cn/zh-CN/docs/serving/main/reference/config#clusterconfig 中的`channel_desc`描述
