### ISSUE TITLE
TEE serving support

### ISSUE THREAD

**Issue by henrysun007** [secretflow/serving#81]
Do you have any plan to run the serving framework in TEE? It seems quite suitable for a serving to run very responsively in a enough secure way, which TEE is quite good at.

**Comment by zimu-yuxi** [comment]
Do you have any business requirements？

**Comment by henrysun007** [comment]
Certainly. The online systems are mostly non-interactive. All the operations, including PSI, inference and other data manipulations, are all chained though apis.

**Comment by zimu-yuxi** [comment]
You can try running it in 'TEE' using the existing image. If it doesn't work, you can try compiling a version, but we haven't tested it yet

**Comment by henrysun007** [comment]
Thanks. I have asked your TEE team and they answered it was not necessary to have such a framework to run serving in TEE. An app can run in TEE directly.
